#!/bin/bash
#SBATCH --job-name=project_name.rtx
#SBATCH --gres=gpu:1
#SBATCH -p RTX
#SBATCH --time=168:00:00
#SBATCH --cpus-per-task=8
#SBATCH -o logs/%j/output.log
#SBATCH --mail-type=ALL
#SBATCH --mail-user=telegram:YOUR_TELEGRAM_ID
#SBATCH --mem=20G


source .venv/bin/activate

mkdir -p logs/${SLURM_JOB_ID}/code
find src/project_name \( -name '*.py' -o -name '*.yaml' \) -exec cp --parents --parents {} logs/${SLURM_JOB_ID}/code/ \;

python -B -m project_name hydra.run.dir=logs/${SLURM_JOB_ID}/hydra
